import Link from "next/link";
import { notFound } from "next/navigation";

import { AppShell } from "../../_components/app-shell";
import { lyricsLibrary, topSongs } from "../../_data/mock-data";

type SongDetailPageProps = {
  params: {
    songId: string;
  };
};

export default function SongDetailPage({ params }: SongDetailPageProps) {
  const explicitSong = lyricsLibrary[params.songId];
  const summary = topSongs.find((item) => item.id === params.songId);

  if (!explicitSong && !summary) {
    notFound();
  }

  const song =
    explicitSong ??
    {
      id: summary!.id,
      title: summary!.title,
      genre: summary!.genre,
      mood: summary!.mood,
      generatedBy: summary!.author,
      createdAt: "Generated recently",
      sections: [
        {
          heading: "[Verse]",
          lines: [summary!.snippet.replace(/"/g, "")],
        },
        {
          heading: "[Chorus]",
          lines: [
            "This lyric was generated with AiLyrics.",
            "Add your verses, bridges and hooks from the generator.",
          ],
        },
      ],
      stats: {
        likes: summary!.likes,
        shares: Math.round(summary!.likes * 0.22),
        copies: Math.round(summary!.likes * 0.16),
      },
      comments: [],
    };

  const related = topSongs
    .filter((item) => item.id !== song.id)
    .slice(0, 4);

  return (
    <AppShell>
      <section className="flex flex-col gap-8 text-white">
        <div className="flex flex-col gap-6 rounded-3xl border border-white/10 bg-white/5 p-8 shadow-[0_25px_55px_rgba(12,10,30,0.55)] md:p-10">
          <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
            <div>
              <p className="text-xs uppercase tracking-[0.3em] text-white/50">
                {song.genre} · {song.mood}
              </p>
              <h1 className="mt-2 text-3xl font-semibold tracking-tight md:text-4xl">
                {song.title}
              </h1>
              <p className="mt-2 text-sm text-white/60">
                {song.createdAt} · Generated by {song.generatedBy}
              </p>
            </div>
            <Link
              href="/app/generate"
              className="self-start rounded-full border border-white/15 px-5 py-2 text-sm text-white/70 transition hover:border-white/35 hover:text-white"
            >
              Remix this lyric
            </Link>
          </div>

          <div className="space-y-6 rounded-3xl border border-white/10 bg-[#18072D]/70 p-6">
            {song.sections.map((section, idx) => (
              <div key={`${section.heading}-${idx}`} className="space-y-3">
                <h2 className="text-sm font-semibold text-purple-200">
                  {section.heading}
                </h2>
                <pre className="whitespace-pre-wrap text-sm leading-7 text-white/80">
                  {section.lines.join("\n")}
                </pre>
              </div>
            ))}
          </div>

          <div className="grid gap-4 rounded-2xl border border-white/10 bg-[#1B0830] p-6 text-sm text-white/70 md:grid-cols-3">
            <div className="flex flex-col gap-1">
              <span className="text-xs uppercase tracking-[0.2em] text-white/40">
                Likes
              </span>
              <span className="text-xl font-semibold text-white">
                {song.stats.likes.toLocaleString()}
              </span>
            </div>
            <div className="flex flex-col gap-1">
              <span className="text-xs uppercase tracking-[0.2em] text-white/40">
                Shares
              </span>
              <span className="text-xl font-semibold text-white">
                {song.stats.shares.toLocaleString()}
              </span>
            </div>
            <div className="flex flex-col gap-1">
              <span className="text-xs uppercase tracking-[0.2em] text-white/40">
                Copies
              </span>
              <span className="text-xl font-semibold text-white">
                {song.stats.copies.toLocaleString()}
              </span>
            </div>
          </div>
        </div>

        {song.comments.length > 0 ? (
          <section className="space-y-6">
            <div className="flex items-center justify-between">
              <h2 className="text-2xl font-semibold">Comments</h2>
              <button className="rounded-full border border-white/15 px-4 py-2 text-sm text-white/70 transition hover:border-white/30 hover:text-white">
                Post comment
              </button>
            </div>
            <div className="space-y-4">
              {song.comments.map((comment) => (
                <div
                  key={comment.id}
                  className="flex gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 text-sm text-white/70"
                >
                  <span className="inline-flex h-10 w-10 items-center justify-center rounded-full bg-purple-500/20 text-white">
                    {comment.author.slice(0, 2).toUpperCase()}
                  </span>
                  <div className="flex flex-1 flex-col gap-1">
                    <div className="flex items-center justify-between text-xs text-white/50">
                      <span className="font-semibold text-white">
                        {comment.author}
                      </span>
                      <span>{comment.timestamp}</span>
                    </div>
                    <p>{comment.message}</p>
                    <div className="flex gap-4 text-xs text-white/40">
                      <button className="transition hover:text-white">
                        Like
                      </button>
                      <button className="transition hover:text-white">
                        Reply
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </section>
        ) : (
          <section className="space-y-4 rounded-3xl border border-white/10 bg-white/5 p-8 text-center text-white/60">
            <h2 className="text-xl font-semibold text-white">
              Be the first to respond
            </h2>
            <p className="text-sm">
              Share your thoughts, suggestions or melodies for this lyric.
            </p>
            <button className="mx-auto mt-4 inline-flex rounded-full border border-white/20 px-4 py-2 text-sm text-white transition hover:border-white/35">
              Start a conversation
            </button>
          </section>
        )}

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">More to explore</h2>
          <div className="grid gap-4 md:grid-cols-2">
            {related.map((item) => (
              <Link
                key={item.id}
                href={`/app/songs/${item.id}`}
                className="flex items-center justify-between rounded-3xl border border-white/10 bg-white/5 px-5 py-4 text-sm text-white/70 transition hover:border-white/25"
              >
                <div className="flex flex-col">
                  <span className="text-white">{item.title}</span>
                  <span className="text-xs text-white/50">
                    {item.genre} · {item.mood}
                  </span>
                </div>
                <span className="inline-flex items-center gap-2 text-xs uppercase tracking-[0.2em] text-white/50">
                  View
                  <span aria-hidden>→</span>
                </span>
              </Link>
            ))}
          </div>
        </section>
      </section>
    </AppShell>
  );
}

