"use client";

import Link from "next/link";
import { useState, useTransition } from "react";

import { API_BASE_URL } from "@/lib/api";

import type { ApiSong, PaginatedResponse } from "../_types";

const PAGE_SIZE = 5;
const DATE_FORMATTER = new Intl.DateTimeFormat("en-GB", {
  day: "2-digit",
  month: "2-digit",
  year: "numeric",
  timeZone: "UTC",
});

function formatRelative(value?: string) {
  if (!value) return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  const diff = Date.now() - date.getTime();
  const minute = 1000 * 60;
  const hour = minute * 60;
  const day = hour * 24;
  if (diff < hour) {
    const mins = Math.max(1, Math.round(diff / minute));
    return `${mins} min ago`;
  }
  if (diff < day) {
    const hrs = Math.round(diff / hour);
    return `${hrs} hr${hrs > 1 ? "s" : ""} ago`;
  }
  return DATE_FORMATTER.format(date).replace(/\//g, ".");
}

async function fetchPage(page: number): Promise<PaginatedResponse<ApiSong>> {
  const res = await fetch(
    `${API_BASE_URL}/songs?page=${page}&limit=${PAGE_SIZE}`,
    {
      cache: "no-store",
    },
  );
  if (!res.ok) {
    throw new Error(`Songs request failed with status ${res.status}`);
  }
  return (await res.json()) as PaginatedResponse<ApiSong>;
}

export function RecentlyGenerated({
  initialPage,
  initialData,
  initialTotalPages,
}: {
  initialPage: number;
  initialData: ApiSong[];
  initialTotalPages: number;
}) {
  const [page, setPage] = useState(initialPage);
  const [songs, setSongs] = useState<ApiSong[]>(initialData);
  const [totalPages, setTotalPages] = useState(initialTotalPages);
  const [isPending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);

  const handlePageChange = (next: number) => {
    if (next < 1 || next > totalPages || next === page) return;
    startTransition(async () => {
      try {
        setError(null);
        const payload = await fetchPage(next);
        setSongs(payload.data);
        setTotalPages(payload.pagination.totalPages || 1);
        setPage(next);
      } catch (err) {
        setError(
          err instanceof Error
            ? err.message
            : "Unable to load more songs right now.",
        );
      }
    });
  };

  return (
    <div className="flex flex-col gap-4">
      {error ? (
        <p className="rounded-2xl border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-200">
          {error}
        </p>
      ) : null}
      <div className="flex flex-col gap-4">
        {songs.length === 0 ? (
          <p className="rounded-2xl border border-white/10 bg-white/5 px-4 py-4 text-sm text-white/60">
            Songs generated by the community will appear here.
          </p>
        ) : null}
        {songs.map((song) => (
          <Link
            key={song._id}
            href={`/app/songs/${song._id}`}
            className="group flex flex-col gap-3 rounded-2xl border border-white/10 bg-[#1B0830]/80 p-5 text-left shadow-[0_14px_35px_rgba(16,23,42,0.5)] transition hover:-translate-y-1 hover:border-white/25 hover:shadow-sky-500/25"
          >
            <div className="flex items-center justify-between text-xs uppercase tracking-[0.18em] text-white/50">
              <span>{song.genre ?? "Unknown"}</span>
              <span>{formatRelative(song.createdAt)}</span>
            </div>
            <div className="flex flex-col gap-2">
              <h3 className="text-base font-semibold text-white">
                {song.title}
              </h3>
              <p className="text-xs text-white/65 sm:text-sm">
                {song.topic ?? song.verses ?? "Freshly generated lyric draft"}
              </p>
            </div>
            <div className="mt-auto flex items-center justify-between text-xs text-white/60">
              <span className="rounded-full bg-white/10 px-3 py-1 text-[10px] uppercase tracking-[0.2em]">
                {song.mood ?? "—"}
              </span>
              <span className="flex items-center gap-2 text-xs uppercase tracking-[0.16em] text-white/50">
                {typeof song.createdBy === "object"
                  ? song.createdBy?.username ??
                    song.createdBy?.email ??
                    "Anonymous"
                  : "Anonymous"}
              </span>
            </div>
          </Link>
        ))}
      </div>
      <div className="flex items-center justify-between rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs text-white/60">
        <button
          type="button"
          disabled={isPending || page <= 1}
          onClick={() => handlePageChange(page - 1)}
          className="rounded-full px-3 py-1 transition hover:text-white disabled:cursor-not-allowed disabled:opacity-40"
        >
          ← Prev
        </button>
        <span>
          Page {page} of {Math.max(totalPages, 1)}
        </span>
        <button
          type="button"
          disabled={isPending || page >= totalPages}
          onClick={() => handlePageChange(page + 1)}
          className="rounded-full px-3 py-1 transition hover:text-white disabled:cursor-not-allowed disabled:opacity-40"
        >
          Next →
        </button>
      </div>
    </div>
  );
}
